### ISSUE TITLE
error during installation on alpine 3.8 with docker

### ISSUE THREAD

**Issue by killmenot** [chrisemunt/tcp-netx#1]
Dockerfile
```
FROM node:10-alpine
RUN apk add --no-cache --virtual .gyp \
    python \
    make \
    g++

RUN npm install tcp-netx

CMD ["echo", "test"]
```

Output:
```
Step 3/4 : RUN npm install tcp-netx
 ---> Running in bf7b73ac5cd1

> tcp-netx@1.0.7-a install /node_modules/tcp-netx
> node-gyp rebuild

make: Entering directory '/node_modules/tcp-netx/build'
  CXX(target) Release/obj.target/tcp-netx/src/tcp-netx.o
In file included from ../src/tcp-netx.cpp:67:0:
/usr/include/sys/errno.h:1:2: warning: #warning redirecting incorrect #include <sys/errno.h> to <errno.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/errno.h> to <errno.h>
  ^~~~~~~
../src/tcp-netx.cpp: In function 'int netx_get_error_message(int, char*, int, int)':
../src/tcp-netx.cpp:2888:21: error: invalid conversion from 'int' to 'char*' [-fpermissive]
       p = strerror_r(error_code, message, (size_t) size);
           ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [tcp-netx.target.mk:99: Release/obj.target/tcp-netx/src/tcp-netx.o] Error 1
make: Leaving directory '/node_modules/tcp-netx/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.9.93-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/tcp-netx
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

**Comment by chrisemunt** [comment]
I've not used Alpine myself, but this sounds like the issue described in...

https://stackoverflow.com/questions/41953104/strerror-r-is-incorrectly-declared-on-alpine-linux

The function in question strerror_r() is only responsible for obtaining the text of an error message from the OS.  Feel free to pull down the code to a local system and try the advice in the above report.  And do let me know if you find what works!

**Comment by chrisemunt** [comment]
Alpine Linux is supported in tcp-netx v1.4.14.
